name: pub_sub
version: 2.0.0
description: Keep application instances in sync with a simple pub/sub API.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/pub_sub
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  json_rpc_2: ^2.0.0
  uuid: ^1.0.0
dev_dependencies:
  test: ^1.0.0